name: generate_mvvm_structure
description: Generate Struktur for State Management with Provider.
version: 0.0.4
repository: https://github.com/ridhocr/generate_state_provder

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  generate_mvvm_structure:

dependencies:
  path: ^1.9.0
